# Generated by Django 5.0.4 on 2026-03-13 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampañaPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre Interno')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto del Correo')),
                ('contenido_html', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('programada_para', models.DateTimeField(blank=True, null=True)),
                ('enviada', models.BooleanField(default=False)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('aperturas_unicas', models.PositiveIntegerField(default=0)),
                ('clicks_totales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierto', models.BooleanField(default=False)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('campaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='marketing.campañapro')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
