# Generated by Django 5.0.4 on 2026-02-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_admin_signature_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(help_text='Enlace de YouTube o Vimeo (ej: https://www.youtube.com/embed/...)'),
        ),
    ]
