# Generated by Django 5.0.4 on 2026-02-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='admin_signature',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.module')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('correct_option', models.IntegerField(choices=[(1, 'Opción 1'), (2, 'Opción 2'), (3, 'Opción 3')])),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz')),
            ],
        ),
    ]
