# Generated by Django 5.0.4 on 2026-02-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
