# Generated by Django 5.0.4 on 2026-02-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_image_alter_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Ejemplo: 🚀, 🎓, 📈', max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
