# Generated by Django 5.0.4 on 2026-03-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequery',
            name='respuesta_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Sugerencia IA Gemini'),
        ),
    ]
