# Generated by Django 5.0.4 on 2026-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_emoji', models.CharField(default='🚀', help_text='Emoji representativo', max_length=10)),
                ('short_description', models.TextField(max_length=300, verbose_name='Resumen Tarjeta')),
                ('long_description', models.TextField(verbose_name='Descripción Detallada')),
                ('banner_image', models.ImageField(upload_to='services/banners/', verbose_name='Imagen Banner')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL Video (YouTube)')),
                ('reels_links', models.TextField(blank=True, help_text='Separados por comas', null=True, verbose_name='IDs de Reels')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Visible?')),
            ],
            options={
                'verbose_name': 'Servicio de Agencia',
                'verbose_name_plural': 'Servicios de Agencia',
                'ordering': ['order'],
            },
        ),
    ]
