# Generated by Django 5.0.4 on 2026-02-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_contactmessage_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='lead_source',
            field=models.CharField(default='Web Directa', max_length=100, verbose_name='Origen del Lead (Campaña)'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='servicio_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.service', verbose_name='Servicio de Interés'),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_regalo_text',
            field=models.CharField(default='¡Descargar mi regalo ahora!', max_length=100, verbose_name='Texto del Botón de Regalo'),
        ),
        migrations.AddField(
            model_name='service',
            name='regalo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='leads/pdfs/', verbose_name='Ebook o Guía PDF'),
        ),
        migrations.AddField(
            model_name='service',
            name='regalo_video_privado',
            field=models.URLField(blank=True, null=True, verbose_name='URL Video Privado (YouTube/Vimeo)'),
        ),
    ]
