# Generated by Django 5.0.4 on 2026-02-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_contactmessage_lead_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='lead_source',
            field=models.CharField(default='Web Directa', max_length=100, verbose_name='Origen del Lead'),
        ),
        migrations.AlterField(
            model_name='service',
            name='regalo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='leads/pdfs/', verbose_name='Ebook o Guía PDF de Regalo'),
        ),
    ]
