# Generated by Django 5.0.4 on 2026-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título de la Sección')),
                ('section_type', models.CharField(choices=[('hero', 'Sección Principal (Hero)'), ('reels', 'Sección de Reels/Videos'), ('clients', 'Logos de Clientes'), ('testimonials', 'Testimonios de Usuarios'), ('services_preview', 'Resumen de Servicios')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Mostrar en el Home?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Sección del Home',
                'verbose_name_plural': 'Estructura del Home',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Usuario')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto (Opcional)')),
                ('rating', models.IntegerField(default=5, verbose_name='Estrellas (1-5)')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='cta_regalo_text',
            field=models.CharField(default='¡Descargar mi regalo ahora!', max_length=100, verbose_name='Texto del Botón'),
        ),
        migrations.AlterField(
            model_name='service',
            name='regalo_video_privado',
            field=models.URLField(blank=True, null=True, verbose_name='URL Video Privado'),
        ),
    ]
