# Generated by Django 5.0.4 on 2026-03-01 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_clientlogo_homesection_usertestimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Reel')),
                ('video_url', models.URLField(verbose_name='Link del Video (Instagram/TikTok/YouTube)')),
                ('thumbnail', models.ImageField(upload_to='reels/thumbs/', verbose_name='Portada del Reel')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['order'], 'verbose_name': 'Estructura del Home', 'verbose_name_plural': 'Estructura del Home'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='logo',
            field=models.ImageField(upload_to='clients/', verbose_name='Logo (Fondo transparente preferible)'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='lead_source',
            field=models.CharField(default='Web Directa', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='servicio_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.service'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Texto/Subtítulo de la sección'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='regalo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='leads/pdfs/', verbose_name='Ebook PDF de Regalo'),
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='comment',
            field=models.TextField(verbose_name='Testimonio'),
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Estrellas'),
        ),
    ]
