# Generated by Django 5.0.4 on 2026-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_homereel_alter_homesection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogo',
            name='url_web',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a su sitio web'),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='logo',
            field=models.ImageField(upload_to='clients/', verbose_name='Foto/Logo del Cliente'),
        ),
    ]
