# Generated by Django 5.0.4 on 2026-03-02 00:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_clientlogo_url_web_alter_clientlogo_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertestimonial',
            options={'verbose_name': 'Testimonio de Usuario', 'verbose_name_plural': 'Testimonios de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usertestimonial',
            name='avatar',
        ),
        migrations.AddField(
            model_name='usertestimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de envío'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertestimonial',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='¿Aprobado para el Home?'),
        ),
        migrations.AddField(
            model_name='usertestimonial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to=settings.AUTH_USER_MODEL, verbose_name='Alumno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(300)], verbose_name='Reseña (Máx 300 caracteres)'),
        ),
        migrations.AlterField(
            model_name='usertestimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre para mostrar'),
        ),
    ]
