# Generated by Django 5.0.4 on 2026-03-02 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_usertestimonial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Artículo')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(verbose_name='Contenido (HTML permitido)')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Imagen de Portada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Blog - Artículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
