# Generated by Django 5.0.4 on 2026-03-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_post_comments_count_post_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Video Lateral (YouTube)'),
        ),
    ]
