# Generated by Django 5.0.4 on 2026-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='¿Leído?'),
        ),
    ]
