# Generated by Django 5.0.4 on 2026-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
